## NumPy ilə Matris Əməliyyatları

In [34]:
import numpy as np

# Matrislər
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrisləri yan-yana çap etmək
for i in range(len(A)):
    print([np.array2string(A[i], separator=' ')[1:-1]], [np.array2string(B[i], separator=' ')[1:-1]])

# Toplama
C = A + B
print("Toplama:\n", C)

['1 2'] ['5 6']
['3 4'] ['7 8']
Toplama:
 [[ 6  8]
 [10 12]]


In [35]:
# Çıxmaq

# Matrisləri yan-yana çap etmək
for i in range(len(A)):
    print([np.array2string(A[i], separator=' ')[1:-1]], [np.array2string(B[i], separator=' ')[1:-1]])

C = A - B
print("Çıxmaq:\n", C)

['1 2'] ['5 6']
['3 4'] ['7 8']
Çıxmaq:
 [[-4 -4]
 [-4 -4]]


In [36]:
# Element-wise Vurma

# Matrisləri yan-yana çap etmək
for i in range(len(A)):
    print([np.array2string(A[i], separator=' ')[1:-1]], [np.array2string(B[i], separator=' ')[1:-1]])

C = A * B
print("Element-wise Vurma:\n", C)

['1 2'] ['5 6']
['3 4'] ['7 8']
Element-wise Vurma:
 [[ 5 12]
 [21 32]]


In [37]:
# Matris Vurma (Alqebraik)

# Matrisləri yan-yana çap etmək
for i in range(len(A)):
    print([np.array2string(A[i], separator=' ')[1:-1]], [np.array2string(B[i], separator=' ')[1:-1]])

C = np.dot(A, B)
# Və ya
C = A @ B
print("Matris Vurma:\n", C)

['1 2'] ['5 6']
['3 4'] ['7 8']
Matris Vurma:
 [[19 22]
 [43 50]]


In [38]:
# Element-wise Bölmə

# Matrisləri yan-yana çap etmək
for i in range(len(A)):
    print([np.array2string(A[i], separator=' ')[1:-1]], [np.array2string(B[i], separator=' ')[1:-1]])

C = A / B
print("Element-wise Bölmə:\n", C)

['1 2'] ['5 6']
['3 4'] ['7 8']
Element-wise Bölmə:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [42]:
# Alqebraik Bölmə (Pseudo-inverse ilə)

# Matrisləri yan-yana çap etmək
for i in range(len(A)):
    print([np.array2string(A[i], separator=' ')[1:-1]], [np.array2string(B[i], separator=' ')[1:-1]])

B_inv = np.linalg.pinv(B)
C = np.dot(A, B_inv)
print("Alqebraik Bölmə:\n", C)

['1 2'] ['5 6']
['3 4'] ['7 8']
Alqebraik Bölmə:
 [[ 3. -2.]
 [ 2. -1.]]
